package trace_test

import (
	"testing"

	"github.com/alexcogojocaru/btracer/trace"
)

func TestHashGeneration(t *testing.T) {
	trace := &trace.Trace{}
	encoded := trace.GenerateID()

	t.Logf("Generated bytes array: %x", encoded)
}
