package trace_test

import (
	"testing"

	"github.com/alexcogojocaru/btracer/trace"
)

func TestHashGeneration(t *testing.T) {
	trace := &trace.Trace{}

	t.Logf("Generated bytes array: %x", trace.TraceID)
}
